### ISSUE TITLE
Es fehlen teilweise die Bilder für die einzelnen Aufgaben unter Pkt. 2.11.3

### ISSUE THREAD

**Issue by norbertschwarz** [christiankral/Grundlagen-der-Elektrotechnik#2]
Sehr geehrter Herr Kral!

In den nachfolgenden Beispielen fehlen bei Ihrem Server die Bilder:

![image](https://github.com/user-attachments/assets/581ef99e-c757-4823-addf-ffadf9abc7bc)

![image](https://github.com/user-attachments/assets/0c46b4a5-232c-4d0a-b779-dabe9b220536)

Herzlichen Dank!

SG

**Comment by christiankral** [comment]
@norbertschwarz Danke für den Hinweis. Ich kümmere mich um die Behebung dieses Problems.

**Comment by norbertschwarz** [comment]
@christiankral Bitte sehr - gern geschehen.

**Comment by christiankral** [comment]
Die Bilder funktionieren jetzt wieder.

**Comment by norbertschwarz** [comment]
@christiankral Herzlichen Dank! SG, Norbert Schwarz
